management:
  security:
    enabled: false
    
    
#spring:
#  profiles:
#    active:
#    - prod
        
test:
  string: YAML ==> ${spring.application.name} 
   
    
    
    # 스페이스 구분자 2번이 하위 레벨로 구분함(yml)
    
    #localhost:8080/env
    #localhost:8080/beans  @Component
    #localhost:8080/autoconfig  @Configuration
    
    
    
    # 환경에따라 프로파일을 나눌수 있다.
    # application.yml (공통)
    # application-dev.yml(개발)
    # application-default.yml(로컬)
    # application-prod.yml(운영)